# Generated by Django 3.1.7 on 2021-03-30 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('link', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('image', models.TextField()),
                ('avgPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('coreClock', models.FloatField()),
                ('coreCount', models.IntegerField()),
                ('coreFamily', models.CharField(max_length=128)),
                ('manufacturer', models.CharField(max_length=128)),
                ('microarchitecture', models.CharField(max_length=128)),
                ('socket', models.CharField(max_length=64)),
                ('buy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcpp.price')),
            ],
        ),
    ]
