# Generated by Django 3.1.7 on 2021-04-01 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pcpp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cpu',
            old_name='avgPrice',
            new_name='minPrice',
        ),
        migrations.RemoveField(
            model_name='cpu',
            name='buy',
        ),
        migrations.AddField(
            model_name='price',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pcpp.cpu'),
            preserve_default=False,
        ),
    ]
