# Generated by Django 3.1.7 on 2021-04-06 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcpp', '0003_case_gpu_memory_motherboard_power'),
    ]

    operations = [
        migrations.AlterField(
            model_name='power',
            name='minPrice',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
