# Generated by Django 3.1.7 on 2021-04-06 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcpp', '0005_auto_20210406_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='power',
            name='Efficiency_Rating',
            field=models.TextField(null=True),
        ),
    ]
