# Generated by Django 3.1.7 on 2021-04-06 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcpp', '0007_auto_20210406_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='minPrice',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='minPrice',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='minPrice',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='memory',
            name='minPrice',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='minPrice',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
