# Generated by Django 3.1.7 on 2021-04-06 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pcpp', '0009_auto_20210406_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lin', models.TextField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='price',
            name='item',
        ),
        migrations.AddField(
            model_name='case',
            name='priceLink',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pcpp.pricelink'),
        ),
        migrations.AddField(
            model_name='cpu',
            name='priceLink',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pcpp.pricelink'),
        ),
        migrations.AddField(
            model_name='gpu',
            name='priceLink',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pcpp.pricelink'),
        ),
        migrations.AddField(
            model_name='memory',
            name='priceLink',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pcpp.pricelink'),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='priceLink',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pcpp.pricelink'),
        ),
        migrations.AddField(
            model_name='power',
            name='priceLink',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pcpp.pricelink'),
        ),
        migrations.AddField(
            model_name='price',
            name='priceLink',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pcpp.pricelink'),
        ),
    ]
