# Generated by Django 3.1.7 on 2021-04-20 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcpp', '0011_pcbuild'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcbuild',
            name='name',
            field=models.CharField(default='test', max_length=256),
            preserve_default=False,
        ),
    ]
